repo: https://github.com/pooneyy/Container-Images-Publisher

ref: main

image_name: squid-buildkit

image_tag: 2026.08.30,resolute-20260811.1,ubuntu-26.04,26.04,latest

build_context: .github/configs/squid

dockerfile: .github/configs/squid/Dockerfile.buildkit

architectures: linux/amd64, linux/arm64, linux/arm/v7, linux/ppc64le, linux/riscv64, linux/s390x

build_args: UBUNTU_VERSION=resolute-20260811.1

build_target: 